services:
  db:
    image: postgres:16-alpine
    container_name: nextunelk-db
    restart: unless-stopped
    env_file: .env.nextunelk.prod
    volumes:
      - nextune_db_data:/var/lib/postgresql/data
    # Port 5432 is now INTERNAL only. No 'ports' mapping to VPS.
    networks:
      - nextune_network

  server:
    image: ghcr.io/ishanardithya/nextunelk/nextunelk-server:latest
    container_name: nextunelk-server
    restart: unless-stopped
    env_file: .env.nextunelk.prod
    ports:
      - "8001:8001" # Exposing the API port specifically
    volumes:
      - ~/logs/prod:/app/logs
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - db
    networks:
      - nextune_network

  client:
    image: ghcr.io/ishanardithya/nextunelk/nextunelk-client:latest
    container_name: nextunelk-client
    restart: unless-stopped
    ports:
      - "3006:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - nextune_network

networks:
  nextune_network:
    driver: bridge

volumes:
  nextune_db_data:
