services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: nextunelk-server
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./server/.env:/app/.env
